name: youtube_player_iframe_example
description: Demonstrates how to use the youtube_player_iframe plugin.
publish_to: 'none'
version: &yp_version 4.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_player_iframe: *yp_version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
